project:
  type: book
  output-dir: docs

format:
  html:
    toc: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  keep-md: false

resources:
  - CNAME

book:
  title: "R Companion to Discrete Choice Methods with Simulation"
  author: 
    - name: "Dan Yavorsky"
      orcid: 0000-0003-4095-6405
      email: dyavorsky@gmail.com
  date: last-modified
  site-url: dcms-r.danyavorsky.com
  repo-url: https://github.com/dyavorsky/dcms-r
  reader-mode: true
  bread-crumbs: false
  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - chapters/03_logit.qmd
    - chapters/04_gev.qmd
    - chapters/05_probit.qmd
    - chapters/06_mixed_logit.qmd
    - chapters/07_variations.qmd
    - chapters/08_maximization.qmd
    - chapters/09_densities.qmd
    - chapters/10_sim_estimation.qmd
    - chapters/11_indiv_params.qmd
    - chapters/12_bayesian.qmd
    - chapters/13_endogeneity.qmd
    - chapters/14_em_algo.qmd
    - chapters/references.qmd

bibliography: references.bib



