project:
  type: book

book:
  title: "R Companion to Discrete Choice Methods with Simulation"
  author: "Dan Yavorsky"
  date: "1/1/2023"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 03_logit.qmd
    - 04_gev.qmd
    - 05_probit.qmd
    - 06_mixed_logit.qmd
    - 07_variations.qmd
    - 08_maximization.qmd
    - 09_densities.qmd
    - 10_sim_estimation.qmd
    - 11_indiv_params.qmd
    - 12_bayesian.qmd
    - 13_endogeneity.qmd
    - 14_em_algo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



